name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Hostinger via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: ftp.hstgr.io
          username: u228385460.technopad.in
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          secure: true
          dangerous-clean-slate: false
          server-dir: /public_html/
          local-dir: ./
